# 概述
程序运行过程中会出现各种错误，可以根据返回值约定错误码来处理，也可以在语言层面提供异常处理机制。

java采用后者。异常可以在任何地方抛出，只需要在上层捕获。

# 继承关系
```
Object
|
|--throwable
   |
   |--Error
   |  |
   |  |--OutOfMemoryError
   |  |--NoClassDefFoundError
   |  |--StackOverflowError
   |  |--...
   |
   |--Exception
      |--RuntimeException
      |  |
      |  |--NullPointException
      |  |--IndexOutOfBoundsException
      |  |--SecurityException
      |  |--...
      |  |--IllegaArgumentException
      |     |
      |     |--NumberFormatException
      |     |...
      |
      |--IOException
      |  |
      |  |--UnsupportedCharsetException
      |  |--FileNotFoundException
      |  |--SocketException
      |
      |--ParseException
      |--GeneralSecurityException
      |--SQLException
      |--TimeoutException
      |--...
```
java规定：
- 必须捕获的异常：Exception及其子类，但不包括RuntimeException及其子类。这种通常称为Checked Exception。
- 不需要捕获的异常：Error及其子类，RuntimeException及其子类。

# 捕获异常
使用try...catch语句。对于Checked 需要捕获或者用throw抛出。捕获异常的catch块可以有多个，发生异常之后依次匹配异常，成功则进入对于的catch块处理，所以catch异常时应该把匹配范围大的Exception写在后面。异常处理逻辑相同可以用 ```|```连接，在同一个catch块中捕获。

如果有无论是否发生异常都要执行的代码，可以放在finally代码块中，这样就必定会执行。

# 异常的传播
当某个方法抛出异常时，如果当前方法没有捕获异常，异常就会被抛到上层调用方法，知道遇到某个try...catch被捕获为止。

通过printStackTrace()可以打印出方法的调用栈。

catch块捕获到异常之后就会执行catch块中的代码，如果会向上抛出新的异常，则会在执行完finally之后在向上抛出。如果在finally中也抛出了异常，则catch块中的抛出异常代码就不会被执行。如果想要获得所有的异常，可以在finally中使用```Throwable.addSuppressed()```把catch中的异常添加进来，再抛出。

# 自定义异常
java标准库定义很多常用的异常，代码中需要抛出异常尽量使用JDK已经定义的异常类型。

大型项目中，可以定义新的异常类型。保持合理的异常继承体系是非常重要的。可以自定义一个BaseException，然后派生出各种业务类型的异常。BaseException需要从一个合适的Exception派生，比如RuntimeException。

# NullPointerException
空指针异常。如果一个对象为null，调用他的方法或访问字段就会产生空指针异常。通常由JVM抛出。

遇到NullPointerException原则是早暴露，早修复，严禁使用catch来隐藏这种编码错误。

# 断言
断言（Assertion）是一种调试程序的方式。java使用```assert```关键字来实现断言。
```java
assert x >= 0 : "x must >= 0";
```
如果断言失败，则抛出AssertionError， 并带上消息x must >= 0。
java断言会导致程序退出。因此不能用于可恢复的程序错误，只应用于开发和测试阶段。对于可恢复的程序错误，应该抛出异常。

同时JVM默认关闭断言指令，遇到assert语句就自动忽略。要执行assert语句，必须给Java虚拟机传递-enableassertions（可简写为-ea）参数启用断言。
```java
java -ea Main.java
```